---
abstract: 'Write Rex::Test like RSpec!'
author:
  - 'Rao Chenlin(chenryn) <rao.chenlin@gmail.com>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rex-Test-Spec
no_index:
  directory:
    - t
    - inc
requires:
  Rex: 0.45
  perl: 5.006
version: 0.05
